apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "velero.fullname" . }}-patch-sa
  namespace: {{ .Release.Namespace }}
  labels: {{ include "velero.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "velero.fullname" . }}-patch-sa
  labels: {{ include "velero.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "patch"]
    resourceNames:
      - {{ include "velero.fullname" . }}-patch-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "velero.fullname" . }}-patch-sa
  labels: {{ include "velero.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "velero.fullname" . }}-patch-sa
subjects:
  - kind: ServiceAccount
    name: {{ include "velero.fullname" . }}-patch-sa
    namespace: {{ .Release.Namespace }}
---
